#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 04 - EeePCとEmacsとSSDと日本語と

  何度目かの再起動で，EeePCが急に静かになった。

  「すまん。私の空冷ファンが壊れたようだ」「いいよ。それよりシャーって音がするけど何？」

  「HDDの音だ。あと，いいよってどういうことだ。ファンが壊れたんだぞ」「そんなので熱暴走するほど君は熱いキャラじゃないでしょ。君のCPUがどうなってるか見たことないの？」「ない」「私はある」「どうなっているんだ」「ガムみたいなシートでキーボード裏にはりつけてあるだけだよ」「…」

  そう。EeePCのCPUにヒートシンクはついておらず，キーボードを介して放熱するようになっている。重い処理をすることがないからか，この後ファンを交換せずともCPU温度が40℃を超えることさえなかった。

  「それよりさ，ファンが壊れたんなら，HDD交換しない？」「SSDにか」「そう。そうすれば完全ファンレスPCだよ」「その金でタブレット買ったほうがいいと思うが」

  今はandroid端末であればtermuxを入れることでLinux環境が構築できる。emacsも動く。

  「私は君を使いたいんだけど」「追加出費は反則じゃないのか」「うるさいのは嫌なの」「何がうるさいんだ」「HDDが」「電源を切ればいいじゃないか」「それじゃワープロの速さに勝てない。だからカーネルの更新以外で電源は落とさないしスリープも使わない」「ワープロワープロというが，emacsはエディタだろう」「私はorg-modeとyatex以外にemacsで文章書いたことがないしこれからも書かない。だからemacsはワープロ」「じゃあ普段なにでプログラムをやっているんだ？」「RStudioとかMATLABとか」「それをemacsで書けばもっと便利になるんじゃないのか？」「あ，いっこemacsでプログラム書いてたの思い出した」「何だ」「SkyrimのModスクリプト」「あ，そう…」

  EeePCの反対を押し切って私は240GBのSSDを換装し，再びDebianのインストールと，emacsのコンパイルという修行をした。なおEeePCの無線モジュールに取り付けられる動画再生支援用のチップがあり，それを使えばEeePCでもフルHDの動画がコマ落ちせずに見られるらしい。

  そして全ての音を失ったEeePCが誕生した。

  <br>
  <br>
  (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-sa/4.0/deed][file:http://i.creativecommons.org/l/by-sa/4.0/88x31.png]]
